module.exports = {
  PROFILE: "Profile",
  EMAIL_TOKEN: "EmailToken",
  SESSION: "Session",
  CONNECTION_PENDING: "ConnectionPending",
  PROJECT: "Project",
  MEDIA: "Media",
  COMMENT: "Comment",
  JOB: "Job",
  CAST_ROLE: "CastRole",
  CREW_ROLE: "CrewRole",
  APPLICATION: "Application",
  CONVERSATION: "Conversation",
  MESSAGE: "Message",
  NOTIFICATION: "Notification",
  REPORT: "Report",
  EARLY_ACCESS: "EarlyAccess",
  PROJECT_INVITE: "ProjectInvite",
  NOTIFICATION_SUBSCRIPTION: "NotificationSubscription",
};
