module.exports = {
  CAMERA: "CAMERA",
  DIRECTION: "DIRECTION",
  PRODUCTION: "PRODUCTION",
  ART: "ART",
  HAIR_AND_MAKEUP: "HAIR_AND_MAKEUP",
  STUNT: "STUNT",
  ACTING: "ACTING",
  WRITING: "WRITING",
  MUSIC_AND_SOUND: "MUSIC_AND_SOUND",
  COSTUME: "COSTUME",
  VFX_SFX: "VFX_SFX",
};
