module.exports = {
  roles: require("./roles"),
  genders: require("./genders"),
  professions: require("./professions"),
  departments: require("./departments"),
  deptSections: require("./dept_sections"),
  projectTypes: require("./project_types"),
  contentTypes: require("./content_types"),
  collections: require("./collections"),
  mappings: require("./mappings"),
  uploadConstraints: require("./upload_constraints"),
  units: require("./units"),
  languages: require("./languages"),
  grades: require("./grades"),
  connectionStatuses: require("./connection_statuses"),
  conversationTypes: require("./conversation_types"),
  notificationTypes: require("./notification_types"),
  fileTypes: require("./file_types"),
};
