module.exports = {
  CONNECTION_REQUEST: "CONNECTION_REQUEST",
  PROJECT_ADMIN: "PROJECT_ADMIN",
  PROJECT_INVITE: "PROJECT_INVITE",
  PROJECT_FOLLOW: "PROJECT_FOLLOW",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  NEW_MEDIA_STAR: "NEW_MEDIA_STAR",
  JOB_UPDATE: "JOB_UPDATE",
  NEW_CHAT_MESSAGE: "NEW_CHAT_MESSAGE",
  NEW_MEDIA_COMMENT: "NEW_MEDIA_COMMENT",
  NEW_MEDIA_COMMENT_STAR: "NEW_MEDIA_COMMENT_STAR",
};
