module.exports = {
  FEATURE_FILM: "FEATURE_FILM",
  SHORT_FILM: "SHORT_FILM",
  WEB_SERIES: "WEB_SERIES",
  COMMERCIAL: "COMMERCIAL",
  TV_SHOW: "TV_SHOW",
  MUSIC_VIDEO: "MUSIC_VIDEO",
  WEDDING_VIDEO: "WEDDING_VIDEO",
  VLOG: "VLOG",
  DOCUMENTARY: "DOCUMENTARY",
  PERFORMING_ARTS: "PERFORMING_ARTS",
  THEATRE: "THEATRE",
  OTHER: "OTHER",
};
